server:
  port: 8085

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: ai-assistant-service

# Custom OpenAI Configuration
app:
  openai:
    api-key: ${OPENAI_API_KEY:your-api-key-here}
    model: gpt-3.5-turbo
    temperature: 0.3
    max-tokens: 500


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Management/Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics