server:
  port: 8080

spring:
  security:
    user:
      name: user
      password: 1234
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/doctors/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/users/**

jwt:
  secret: myVeryLongSecretKeyThatIsAtLeast32CharactersLongForJWTSecurity
  expiration: 86400000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
