server:
  port: 8082

spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:mysql://localhost:3306/medisync_patient_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
