package com.medisync.enums;

public enum MedicalSpecialization {
    CARDIOLOGY,
    DERMATOLOGY,
    NEUROLOGY,
    ORTHOPEDICS,
    PEDIATRICS,
    PSYCHIATRY,
    RADIOLOGY,
    ONCOLOGY,
    OPHTHALMOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    NEPHROLOGY,
    UROLOGY,
    PULMONOLOGY,
    RHEUMATOLOGY,
    INFECTIOUS_DISEASES,
    HEMATOLOGY,
    ALLERGY_IMMUNOLOGY,
    OTOLARYNGOLOGY,
    GENERAL_SURGERY
}

