server:
  port: 8761

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false